/**
 * Proud Indian style tokens. One source of truth: edit the TS, then run `bun run tokens` (`bun run build` also runs
 * it) to regenerate theme.css (Tailwind v4 @theme), tokens.css (plain custom properties) and tokens.json
 * (W3C design tokens). `bun run tokens:check` fails if any is stale.
 */
import { components } from "./components";
import {
  alpha,
  border,
  breakpoint,
  color,
  container,
  display,
  font,
  leading,
  motion,
  productColor,
  radius,
  radiusShape,
  rgb,
  space,
  text,
  tracking,
  weight,
  z,
} from "./primitives";
import { semantic, semanticColor, shadow } from "./semantic";

export * from "./primitives";
export { components } from "./components";
export { semantic, semanticColor, shadow } from "./semantic";

const kebab = (s: string) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([a-z])(\d)/g, "$1-$2")
    .toLowerCase();
/** 13.5 -> "13-5" (custom property names cannot contain a dot) */
const step = (n: number) => String(n).replace(".", "-");

export type Group = { title: string; theme: boolean; vars: [string, string][] };

const g = (
  title: string,
  theme: boolean,
  vars: [string, string | number][]
): Group => ({
  title,
  theme,
  vars: vars.map(([k, val]) => [k, String(val)]),
});

/** Every custom property, grouped for theme.css, tokens.css and the style guide. */
export function tokenGroups(): Group[] {
  const alphas: [string, string][] = [];
  for (const [name, steps] of Object.entries(alpha)) {
    for (const [pct, a] of Object.entries(steps)) {
      alphas.push([
        `color-${kebab(name)}-a${pct}`,
        `rgba(${rgb[name as keyof typeof rgb]},${a})`,
      ]);
    }
  }
  return [
    // ---- Tailwind theme (theme.css)
    g(
      "Colour",
      true,
      Object.entries(color).map(([k, val]) => [`color-${kebab(k)}`, val])
    ),
    g("Colour alpha", true, alphas),
    g(
      "Colour roles",
      true,
      Object.entries(semanticColor).map(([k, val]) => [`color-${k}`, val])
    ),
    g(
      "Product colour",
      true,
      Object.entries(productColor).map(([k, val]) => [`color-${kebab(k)}`, val])
    ),
    g(
      "Font family",
      true,
      Object.entries(font).map(([k, val]) => [`font-${k}`, val])
    ),
    g(
      "Font weight",
      true,
      Object.entries(weight).map(([k, val]) => [`font-weight-${k}`, val])
    ),
    g("Type scale", true, [
      ...text.flatMap((n): [string, string][] => [
        [`text-${step(n)}`, `${n}px`],
        [`text-${step(n)}--line-height`, "normal"],
      ]),
      ...Object.entries(display).flatMap(([k, val]): [string, string][] => [
        [`text-${k}`, val],
        [`text-${k}--line-height`, "normal"],
      ]),
    ]),
    g(
      "Line height",
      true,
      Object.entries(leading).map(([k, val]) => [`leading-${k}`, val])
    ),
    g(
      "Letter spacing",
      true,
      Object.entries(tracking).map(([k, val]) => [`tracking-${k}`, val])
    ),
    g("Radius", true, [
      ...radius.map((n): [string, string] => [`radius-${n}`, `${n}px`]),
      ["radius-pill", radiusShape.pill],
      ["radius-round", radiusShape.round],
    ]),
    g(
      "Shadow",
      true,
      Object.entries(shadow).map(([k, val]) => [`shadow-${k}`, val])
    ),
    g(
      "Breakpoint",
      true,
      Object.entries(breakpoint).map(([k, val]) => [
        `breakpoint-${k}`,
        `${val}px`,
      ])
    ),
    g(
      "Container",
      true,
      Object.entries(container).map(([k, val]) => [`container-${k}`, val])
    ),
    g(
      "Easing",
      true,
      Object.entries(motion.ease).map(([k, val]) => [`ease-${k}`, val])
    ),
    // ---- plain custom properties (tokens.css)
    g(
      "Border width",
      false,
      Object.entries(border).map(([k, val]) => [`border-${k}`, val])
    ),
    g(
      "Space (hand-written CSS)",
      false,
      space.map((n) => [`space-${n}`, `${n}px`])
    ),
    g(
      "Z-index",
      false,
      Object.entries(z).map(([k, val]) => [`z-${kebab(k)}`, val])
    ),
    g(
      "Duration",
      false,
      Object.entries(motion.duration).map(([k, val]) => [`dur-${k}`, val])
    ),
    g(
      "Loop",
      false,
      Object.entries(motion.loop).map(([k, val]) => [`loop-${k}`, val])
    ),
    g("Semantic", false, Object.entries(semantic)),
    g("Component", false, Object.entries(components)),
  ];
}

const HEADER =
  "/* GENERATED by @proudindian/design tokens/build.ts from tokens/*.ts. Do not edit; run `bun run tokens`. */\n";

const body = (groups: Group[]) =>
  groups
    .map(
      (grp) =>
        ` /* ${grp.title} */\n${grp.vars.map(([k, val]) => ` --${k}:${val};`).join("\n")}`
    )
    .join("\n");

/** Tailwind v4 theme. `static` emits every variable, used or not, so hand-written CSS can rely on them. */
export function themeCss(): string {
  return `${HEADER}@theme static {\n${body(tokenGroups().filter((x) => x.theme))}\n}\n`;
}

export function tokensCss(): string {
  return `${HEADER}:root{\n${body(tokenGroups().filter((x) => !x.theme))}\n}\n`;
}
