/**
 * scope.css: `.pi-brand`, an optional scope that sets the brand text font (Geist) on plain text inside it.
 *
 * Until 0.2.0 this was a "brand island" that re-declared the theme keys the brand shared with pi-dash's shadcn/ui
 * theme (`--font-sans`, `--font-display`, `--color-accent`, `--color-muted`). Those tokens are now named
 * `--font-pi-sans`, `--font-pi-display`, `--color-accent-ink` and `--color-text-muted`, so both themes load side by side
 * and the .pi-* primitives and React components render on-brand anywhere, with no wrapper. The class is kept so
 * existing `className="pi-brand"` wrappers stay valid; it no longer redefines any variable.
 *
 * `assertNoShadcnClash` keeps it that way: the token build fails if a brand theme key reuses one of pi-dash's names.
 */
import type { Group } from "./index";

/** Every `@theme inline` key of pi-dash's shadcn/ui theme (pi-dash packages/design-system/styles.css). */
export const SHADCN_THEME_KEYS = [
  "font-sans",
  "font-display",
  "ease-out-expo",
  "ease-out-quart",
  "ease-out-sheet",
  "radius-sm",
  "radius-md",
  "radius-lg",
  "radius-xl",
  "radius-2xl",
  "radius-3xl",
  "radius-4xl",
  ...[
    "background",
    "foreground",
    "card",
    "card-foreground",
    "popover",
    "popover-foreground",
    "primary",
    "primary-foreground",
    "secondary",
    "secondary-foreground",
    "muted",
    "muted-foreground",
    "accent",
    "accent-foreground",
    "destructive",
    "destructive-foreground",
    "border",
    "input",
    "ring",
    "chart-1",
    "chart-2",
    "chart-3",
    "chart-4",
    "chart-5",
    "sidebar",
    "sidebar-foreground",
    "sidebar-primary",
    "sidebar-primary-foreground",
    "sidebar-accent",
    "sidebar-accent-foreground",
    "sidebar-border",
    "sidebar-ring",
    "brand",
    "brand-foreground",
    "success",
    "success-foreground",
    "info",
    "info-foreground",
    "warning",
    "warning-foreground",
    "invert",
    "invert-foreground",
  ].map((c) => `color-${c}`),
] as const;

export function assertNoShadcnClash(groups: Group[]): void {
  const shadcn = new Set<string>(SHADCN_THEME_KEYS);
  const clash = groups
    .filter((g) => g.theme)
    .flatMap((g) => g.vars.map(([k]) => k))
    .filter((k) => shadcn.has(k));
  if (clash.length > 0) {
    throw new Error(
      `tokens: brand theme keys clash with pi-dash's shadcn/ui theme: ${clash.map((k) => `--${k}`).join(", ")}`
    );
  }
}

export function scopeCss(groups: Group[]): string {
  assertNoShadcnClash(groups);
  return `/* GENERATED by @proudindian/design tokens/build.ts from tokens/*.ts. Do not edit; run \`bun run tokens\`. */
/* Optional brand text scope. No theme key is shared with shadcn/ui, so brand components need no wrapper. See tokens/scope.ts. */
.pi-brand{
 font-family:var(--font-pi-sans);
}
`;
}
