/**
 * Generate react/generated/{doodles,logo}.ts from illustrations/*.svg and logo/{svg,seals}/*.svg, so the React
 * Doodle, Lockup and Seal components inline the exact package artwork.
 *   bun run react:assets          write
 *   bun run react:assets --check  exit 1 if stale (part of `bun run check`)
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "react", "generated");

const camel = (k: string) =>
  k.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());

interface Art {
  viewBox: string;
  attrs: Record<string, string>;
  body: string;
}

/** Split an SVG file into its root attributes (React-cased) and inner markup. */
function parse(file: string, keepRoot: string[]): Art {
  const src = readFileSync(file, "utf8").trim();
  const open = src.match(/^<svg\b[^>]*>/)?.[0];
  if (!open) throw new Error(`${file}: no <svg>`);
  const attrs: Record<string, string> = {};
  let viewBox = "";
  for (const [, k, v] of open.matchAll(/([\w:-]+)="([^"]*)"/g)) {
    if (!k || v === undefined) continue;
    if (k === "viewBox") viewBox = v;
    else if (keepRoot.includes(k)) attrs[camel(k)] = v;
  }
  const body = src
    .slice(open.length, src.lastIndexOf("</svg>"))
    .replace(/<title>[\s\S]*?<\/title>/, "")
    .trim();
  return { viewBox, attrs, body };
}

const HEADER =
  "// GENERATED by scripts/build-react-assets.ts from the package artwork. Do not edit; run `bun run react:assets`.\n";

const ser = (o: Record<string, Art>) => JSON.stringify(o, null, 1);
const union = (keys: string[]) =>
  keys.map((k) => JSON.stringify(k)).join(" | ");

// ---- doodles
const ROOT_ATTRS = [
  "fill",
  "stroke",
  "stroke-width",
  "stroke-linecap",
  "stroke-linejoin",
  "preserveAspectRatio",
];
const manifest = JSON.parse(
  readFileSync(join(ROOT, "illustrations", "manifest.json"), "utf8")
) as {
  name: string;
  file: string;
  title: string;
}[];
const doodles: Record<string, Art> = {};
for (const d of manifest)
  doodles[d.name] = parse(join(ROOT, "illustrations", d.file), ROOT_ATTRS);
const titles = Object.fromEntries(manifest.map((d) => [d.name, d.title]));
const doodlesTs = `${HEADER}
export interface Art {
  readonly viewBox: string;
  readonly attrs: Readonly<Record<string, string>>;
  readonly body: string;
}

export type DoodleName = ${union(Object.keys(doodles))};

export const doodleArt: Readonly<Record<DoodleName, Art>> = ${ser(doodles)};

export const doodleTitles: Readonly<Record<DoodleName, string>> = ${JSON.stringify(titles, null, 1)};

export const doodleNames = Object.keys(doodleArt) as DoodleName[];
`;

// ---- logo
const LOCKUPS = [
  "pi-lockup",
  "pi-lockup-compact",
  "pi-stacked",
  "pi-symbol",
  "pi-wordmark",
];
const logo: Record<string, Art> = {};
for (const f of readdirSync(join(ROOT, "logo", "svg")).toSorted()) {
  const name = f.replace(/\.svg$/, "");
  const base = name.replace(/-(mono|reversed)$/, "");
  if (LOCKUPS.includes(base))
    logo[name] = parse(join(ROOT, "logo", "svg", f), ["color"]);
}
const seals: Record<string, Art> = {};
for (const f of readdirSync(join(ROOT, "logo", "seals")).toSorted()) {
  if (/stamp-production|SCREEN-ONLY/.test(f)) continue; // print and mock-up artwork stay files
  seals[f.replace(/\.svg$/, "")] = parse(join(ROOT, "logo", "seals", f), [
    "color",
  ]);
}
const logoTs = `${HEADER}
import type { Art } from "./doodles";

export type LogoFile = ${union(Object.keys(logo))};
export type SealFile = ${union(Object.keys(seals))};

export const logoArt: Readonly<Record<LogoFile, Art>> = ${ser(logo)};

export const sealArt: Readonly<Record<SealFile, Art>> = ${ser(seals)};
`;

const out: [string, string][] = [
  [join(OUT, "doodles.ts"), doodlesTs],
  [join(OUT, "logo.ts"), logoTs],
];
const check = process.argv.includes("--check");
let stale = false;
mkdirSync(OUT, { recursive: true });
for (const [file, content] of out) {
  let cur = "";
  try {
    cur = readFileSync(file, "utf8");
  } catch {
    cur = "";
  }
  if (cur === content) continue;
  if (check) {
    console.error(`stale: ${file} (run \`bun run react:assets\`)`);
    stale = true;
  } else {
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
if (stale) process.exit(1);
if (check) console.log("react assets: up to date");
